apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlapp-deployment
  labels:
    app: mlapp-pods
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlapp-pods
  template:
    metadata:
      labels:
        app: mlapp-pods
    spec:
      containers:
        - name: mlapp-container
          image: igorromaric/mlapp
          ports:
            - containerPort: 5000
